#API
course:
     type:     rest
     prefix:   api/v1
     resource: ApiBundle\Controller\CourseController

session:
     type:     rest
     prefix:   api/v1
     resource: ApiBundle\Controller\SessionController

trueorfalse:
     type:     rest
     prefix:   api/v1
     resource: ApiBundle\Controller\TrueorfalseController

shortanswer:
     type:     rest
     prefix:   api/v1
     resource: ApiBundle\Controller\ShortanswerController

multiplechoice:
     type:    rest
     prefix:  api/v1
     resource: ApiBundle\Controller\MultiplechoiceController


mobile:
     type:    rest
     prefix:  api/v1
     resource: ApiBundle\Controller\MobileController
